---
name: Build App Image

on:
  push:
    branches:
      - main
      - staging
  # pull_request_target:
  #   branches:
  #     - main

jobs:
  docker-image-builds:
    name: Docker image builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Episode 1.
          - episode: '01'
            dockerfile: Dockerfile
            repo: ibstorm
            tag: v0.0.1

          # # Episode 2. no need any more
          # - episode: '02'
          #   dockerfile: Dockerfile
          #   repo: kube101
          #   tag: hello-go
          # - episode: '02'
          #   dockerfile: Dockerfile
          #   repo: kube101-go
          #   tag: '1.0.0'

          # # Episode 3.
          # - episode: '03'
          #   dockerfile: Dockerfile
          #   repo: kube101-go
          #   tag: '1.1.0'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      
#      - name: Set tag version
#        uses: auto-generate-next-release-tag@v1
#        id: generate-tag-version
#
#      - name: Create tag
#        run: |
#          git tag ${{ steps.generate-tag-version.outputs.next_release_tag }}
#          git push origin ${{ steps.generate-tag-version.outputs.next_release_tag }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./app-${{ matrix.episode }}/
          file: ./app-${{ matrix.episode }}/${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bahajian/${{ matrix.repo }}:latest
